version: '3.8'

services:
  web:
    image: 'flask-oauth-image'
    env_file: .env
    environment:
      - APP_SECRET_KEY=${APP_SECRET_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    ports:
      - 80:5000
    build:
      context: .
      dockerfile: Dockerfile